In [56]:
import numpy as np
import pandas as pd
df = pd.read_csv('marketing_data.csv')
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country
0,1826,1970,Graduation,Divorced,84835.0,0,0,16-06-2014,0,189,...,6,1,0,0,0,0,0,1,0,Spain
1,1,1961,Graduation,Single,57091.0,0,0,15-06-2014,0,464,...,7,5,0,0,0,0,1,1,0,Canada
2,10476,1958,Graduation,Married,67267.0,0,1,13-05-2014,0,134,...,5,2,0,0,0,0,0,0,0,USA
3,1386,1967,Graduation,Together,32474.0,1,1,11-05-2014,0,10,...,2,7,0,0,0,0,0,0,0,Australia
4,5371,1989,Graduation,Single,21474.0,1,0,08-04-2014,0,6,...,2,7,1,0,0,0,0,1,0,Spain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,07-03-2013,99,372,...,11,4,0,0,0,0,0,0,0,USA
2236,5263,1977,2n Cycle,Married,31056.0,1,0,22-01-2013,99,5,...,3,8,0,0,0,0,0,0,0,Spain
2237,22,1976,Graduation,Divorced,46310.0,1,0,03-12-2012,99,185,...,5,8,0,0,0,0,0,0,0,Spain
2238,528,1978,Graduation,Married,65819.0,0,0,29-11-2012,99,267,...,10,3,0,0,0,0,0,0,0,India
2239,4070,1969,PhD,Married,94871.0,0,2,01-09-2012,99,169,...,4,7,0,1,1,0,0,1,0,Canada

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4    Income              2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Response             2240 non-null   int64
 26  Complain             2240 non-null   int64
 27  Country              2240 non-null   str
dtypes: float64(1), int64(23), str(4)
memory usage: 558.1 KB

In [58]:
df.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,2.662054,5.790179,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.149107,0.009375
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.923101,3.250958,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.356274,0.096391
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,0.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,2.000000,5.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,4.000000,8.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,28.000000,13.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [59]:
df[df[" Income "].isna()]

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country
134,8996,1957,PhD,Married,NaN,2,1,19-11-2012,4,230,...,8,9,0,0,0,0,0,0,0,Germany
262,1994,1983,Graduation,Married,NaN,1,0,15-11-2013,11,5,...,2,7,0,0,0,0,0,0,0,USA
394,3769,1972,PhD,Together,NaN,1,0,02-03-2014,17,25,...,3,7,0,0,0,0,0,0,0,Australia
449,5255,1986,Graduation,Single,NaN,1,0,20-02-2013,19,5,...,0,1,0,0,0,0,0,0,0,Australia
525,8268,1961,PhD,Married,NaN,0,1,11-07-2013,23,352,...,7,6,0,0,0,0,0,0,0,Canada
590,10629,1973,2n Cycle,Married,NaN,1,0,14-09-2012,25,25,...,3,8,0,0,0,0,0,0,0,Germany
899,10475,1970,Master,Together,NaN,0,1,01-04-2013,39,187,...,6,5,0,0,0,0,0,0,0,USA
997,9235,1957,Graduation,Single,NaN,1,1,27-05-2014,45,7,...,2,7,0,0,0,0,0,0,0,Germany
1096,4345,1964,2n Cycle,Single,NaN,1,1,12-01-2014,49,5,...,2,7,0,0,0,0,0,0,0,Australia
1185,7187,1969,Master,Together,NaN,1,1,18-05-2013,52,375,...,4,3,0,0,0,0,0,0,0,Australia
1213,8720,1978,2n Cycle,Together,NaN,0,0,12-08-2012,53,32,...,1,0,0,1,0,0,0,0,0,India
1312,8557,1982,Graduation,Single,NaN,1,0,17-06-2013,57,11,...,3,6,0,0,0,0,0,0,0,Australia
1515,2863,1970,Graduation,Single,NaN,1,2,23-08-2013,67,738,...,10,7,0,1,0,1,0,0,0,Spain
1558,2437,1989,Graduation,Married,NaN,0,0,03-06-2013,69,861,...,12,3,0,1,0,1,0,0,0,Spain
1693,5250,1943,Master,Widow,NaN,0,0,30-10-2013,75,532,...,11,1,0,0,1,0,0,1,0,Australia
1804,7281,1959,PhD,Single,NaN,0,0,05-11-2013,80,81,...,4,2,0,0,0,0,0,0,0,Australia
1858,1612,1981,PhD,Single,NaN,1,0,31-05-2013,82,23,...,3,6,0,0,0,0,0,0,0,Australia
1863,5079,1971,Graduation,Married,NaN,1,1,03-03-2013,82,71,...,3,8,0,0,0,0,0,0,0,Australia
1880,10339,1954,Master,Together,NaN,0,1,23-06-2013,83,161,...,4,6,0,0,0,0,0,0,0,Australia
1967,5798,1973,Master,Together,NaN,0,0,23-11-2013,87,445,...,8,1,0,0,0,0,0,0,0,Germany
1983,2902,1958,Graduation,Together,NaN,1,1,03-09-2012,87,19,...,3,5,0,0,0,0,0,0,0,Australia
2139,3117,1955,Graduation,Single,NaN,0,1,18-10-2013,95,264,...,5,7,0,0,0,0,0,0,0,Australia
2165,7244,1951,Graduation,Single,NaN,2,1,01-01-2014,96,48,...,4,6,0,0,0,0,0,0,0,Australia
2170,1295,1963,Graduation,Married,NaN,0,1,11-08-2013,96,231,...,7,4,0,0,0,0,0,0,0,Canada

In [60]:
#data cleaning
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns

Index(['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome',
       'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1',
       'acceptedcmp2', 'response', 'complain', 'country'],
      dtype='str')

In [61]:
#filling null values
df['income'] = df['income'].fillna(df['income'].median())
df['income']

0       84835.0
1       57091.0
2       67267.0
3       32474.0
4       21474.0
         ...
2235    66476.0
2236    31056.0
2237    46310.0
2238    65819.0
2239    94871.0
Name: income, Length: 2240, dtype: float64

Creating New Columns

In [62]:
#creating customer age column

df['dt_customer'] = pd.to_datetime(df['dt_customer'],  format='%d-%m-%Y')
df['customer_year'] = df['dt_customer'].dt.year
df['customer_month'] = df['dt_customer'].dt.month
df['age'] = df['customer_year'] - df['year_birth']
df[['age','customer_year', 'customer_month']]

      age  customer_year  customer_month
0      44           2014               6
1      53           2014               6
2      56           2014               5
3      47           2014               5
4      25           2014               4
...   ...            ...             ...
2235   37           2013               3
2236   36           2013               1
2237   36           2012              12
2238   34           2012              11
2239   43           2012               9

[2240 rows x 3 columns]

In [63]:
#creating total spending by each customer

spending_cols = ['mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods']

df['total_spend'] = df[spending_cols].sum(axis = 1)

In [64]:
#creating total purchase by each cutomer

purchase_cols = ['numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases']

df['total_purchase'] = df[purchase_cols].sum(axis = 1)

In [65]:
#creating total childern column

df['total_childern'] = df['kidhome'] + df['teenhome']

In [66]:
#creating campaign acceptances column

campaign_cols = [
    'acceptedcmp1',
    'acceptedcmp2',
    'acceptedcmp3',
    'acceptedcmp4',
    'acceptedcmp5'
]

df['campaign_acceptance'] = df[campaign_cols].sum(axis = 1)

In [72]:
#creating web conversion rate column

df['web_conversion_rate'] = np.where(
    df['numwebvisitsmonth'] > 0,
    df['numwebpurchases'] / df['numwebvisitsmonth'],
    np.nan
)

In [77]:
df['web_visit_flag'] = (df['numwebvisitsmonth'] > 0).astype(int)

Checking data before loading into SQL

In [78]:
df.isnull().sum()

id                      0
year_birth              0
education               0
marital_status          0
income                  0
kidhome                 0
teenhome                0
dt_customer             0
recency                 0
mntwines                0
mntfruits               0
mntmeatproducts         0
mntfishproducts         0
mntsweetproducts        0
mntgoldprods            0
numdealspurchases       0
numwebpurchases         0
numcatalogpurchases     0
numstorepurchases       0
numwebvisitsmonth       0
acceptedcmp3            0
acceptedcmp4            0
acceptedcmp5            0
acceptedcmp1            0
acceptedcmp2            0
response                0
complain                0
country                 0
customer_year           0
customer_month          0
age                     0
total_spend             0
total_purchase          0
total_childern          0
campaign_acceptance     0
web_conversion_rate    11
web_visit_flag          0
dtype: int64

In [82]:
df.duplicated().sum()

np.int64(0)

In [83]:
df.dtypes

id                              int64
year_birth                      int64
education                         str
marital_status                    str
income                        float64
kidhome                         int64
teenhome                        int64
dt_customer            datetime64[us]
recency                         int64
mntwines                        int64
mntfruits                       int64
mntmeatproducts                 int64
mntfishproducts                 int64
mntsweetproducts                int64
mntgoldprods                    int64
numdealspurchases               int64
numwebpurchases                 int64
numcatalogpurchases             int64
numstorepurchases               int64
numwebvisitsmonth               int64
acceptedcmp3                    int64
acceptedcmp4                    int64
acceptedcmp5                    int64
acceptedcmp1                    int64
acceptedcmp2                    int64
response                        int64
complain                        int64
country                           str
customer_year                   int32
customer_month                  int32
age                             int64
total_spend                     int64
total_purchase                  int64
total_childern                  int64
campaign_acceptance             int64
web_conversion_rate           float64
web_visit_flag                  int64
dtype: object

In [84]:
df['education'].value_counts()

education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [86]:
df['marital_status'].value_counts()

marital_status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
YOLO          2
Absurd        2
Name: count, dtype: int64

In [87]:
df['country'].value_counts()

country
Spain           1095
Saudi Arabia     337
Canada           268
Australia        160
India            148
Germany          120
USA              109
Mexico             3
Name: count, dtype: int64

In [88]:
binary_cols = [
    'acceptedcmp1',
    'acceptedcmp2',
    'acceptedcmp3',
    'acceptedcmp4',
    'acceptedcmp5',
    'response',
    'complain'
]

for col in binary_cols:
    print(col, df[col].unique())

acceptedcmp1 [0 1]
acceptedcmp2 [0 1]
acceptedcmp3 [0 1]
acceptedcmp4 [0 1]
acceptedcmp5 [0 1]
response [1 0]
complain [0 1]

In [91]:
df.head()

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,country,customer_year,customer_month,age,total_spend,total_purchase,total_childern,campaign_acceptance,web_conversion_rate,web_visit_flag
0,1826,1970,Graduation,Divorced,84835.0,0,0,2014-06-16,0,189,...,Spain,2014,6,44,1190,14,0,0,4.000000,1
1,1,1961,Graduation,Single,57091.0,0,0,2014-06-15,0,464,...,Canada,2014,6,53,577,17,0,1,1.400000,1
2,10476,1958,Graduation,Married,67267.0,0,1,2014-05-13,0,134,...,USA,2014,5,56,251,10,1,0,1.500000,1
3,1386,1967,Graduation,Together,32474.0,1,1,2014-05-11,0,10,...,Australia,2014,5,47,11,3,2,0,0.142857,1
4,5371,1989,Graduation,Single,21474.0,1,0,2014-04-08,0,6,...,Spain,2014,4,25,91,6,1,1,0.428571,1

In [92]:
df = df.drop(columns=['year_birth'])

In [93]:
df.columns

Index(['id', 'education', 'marital_status', 'income', 'kidhome', 'teenhome',
       'dt_customer', 'recency', 'mntwines', 'mntfruits', 'mntmeatproducts',
       'mntfishproducts', 'mntsweetproducts', 'mntgoldprods',
       'numdealspurchases', 'numwebpurchases', 'numcatalogpurchases',
       'numstorepurchases', 'numwebvisitsmonth', 'acceptedcmp3',
       'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1', 'acceptedcmp2',
       'response', 'complain', 'country', 'customer_year', 'customer_month',
       'age', 'total_spend', 'total_purchase', 'total_childern',
       'campaign_acceptance', 'web_conversion_rate', 'web_visit_flag'],
      dtype='str')

Loading Data In SQL

In [95]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL

username = "postgres"
password = "rohit#88"
host = "localhost"
port = "5432"
database = "marketing_data"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL

table_name = "marketing"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'marketing' in database 'marketing_data'.